# -*- coding: utf-8 -*-
"""predictive_maintenance_DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eeBoQ4zn048XCKuYeAwJ1YkPykN6jWOy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data=pd.read_csv("/content/drive/MyDrive/predictive_maintenance.csv")
data.head()

data.drop(columns=['UDI'], inplace=True)
data=data.drop('Target',axis=1)
data=data.drop("Product ID",axis=1)
data.head()

data['Type'].unique()

print(sorted(data['Tool wear [min]'].unique()))

data['Type']=data['Type'].replace('L',1).replace('M',2).replace('H',3)
data.head()

X = data.drop('Failure Type',axis=1)
y=data['Failure Type']

x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.4, random_state= 60 )

model=DecisionTreeClassifier(criterion="entropy")
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
Acc=accuracy_score(y_test,y_pred)
print("Accuracy is (Information Gain) : ",Acc)

prediction = pd.DataFrame(y_pred, columns=['pred']).to_csv('prediction1.csv')

import pickle
pickle.dump(model, open('model.pkl', 'wb'))
pickled_model = pickle.load(open('model.pkl', 'rb'))

pickled_model.predict(x_test)